### ISSUE TITLE
VideoFileProcessor fails to split .wmv video to frames

### ISSUE THREAD

**Issue by 70Null07** [askatmaster/MediaFileProcessor#5]
![image](https://github.com/askatmaster/MediaFileProcessor/assets/76547066/064fca21-9655-45f0-befe-f1a143eb4f72)

When i'm trying to split 80 seconds video to 16 images (1 frame per 5 seconds) VideoFileProcessor does not creating any images after 60 seconds of video.

![image](https://github.com/askatmaster/MediaFileProcessor/assets/76547066/5fe18a35-3e6c-4c29-a27a-5067c959bd24)

**Comment by 70Null07** [comment]
The problem is in class VideoProcessingSettings, method  public VideoProcessingSettings Seek(TimeSpan seek)
    {
        _stringBuilder.Append($" -ss {seek.TotalSeconds:00:00:00.000} ".Replace(",", "."));
        return this;
    }
ffmpeg does not accept 60 or more seconds, method must parse input seconds to 00:1:00.000, not 00:00:60.000

**Comment by askatmaster** [comment]
Hi, thanks for this issue, i apologize for the late reply, the fact is that the code provided to you was up-to-date in version 1.0.2 of the nuget package. I updated the nuget package to version 1.0.3 and this problem is fixed in it, now it generates the timing correctly.
I've also made corrections and updated the Readme file.
In the current version, the GetFrameFromVideoAsync method has been replaced by ExtractFrameFromVideoAsync.

Sincerely, Askhat.

**Comment by askatmaster** [comment]
![image](https://github.com/askatmaster/MediaFileProcessor/assets/62430231/868b0e4f-303c-4023-8263-b49952db7f7f)
![image](https://github.com/askatmaster/MediaFileProcessor/assets/62430231/aeae2443-4b03-4012-8716-ee50bb74f94d)
Here are the screenshots from the debug.
Code:
```
const string filePath = @"D:\Projects\MediaFileProcessor\MediaFileProcessor\ConsoleTest\bin\Debug\net7.0\testFiles\issue.mp4";

var videoProcessor = new VideoFileProcessor();
var nf = new MediaFile(filePath);

await videoProcessor.ExtractFrameFromVideoAsync(TimeSpan.FromMilliseconds(90000), nf, @$"issueTest\img_split_{90000}.jpg");
```
